FROM archlinux:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
        git p7zip nodejs npm python bubblewrap \
        base-devel && \
    npm install -g @electron/asar && \
    pacman -Scc --noconfirm

WORKDIR /mnt/repo
